version: '3.8'
services:

  stats-server:
    build: stats-server/
    container_name: stats-server
    depends_on:
      - stats_db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test


  stats_db:
    container_name: stats_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /home/aleksandr/dev/stats_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 65s
      timeout: 65s
      retries: 65
    volumes:
      - ./stats-server/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  ewm-service:
    build: ewm-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090


  ewm-db:
    container_name: ewm-db
    image: postgres
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /home/aleksandr/dev/ewm-db
    volumes:
      - ./ewm-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql